TrackMyExpenses/Models/ErrorViewModel.cs
namespace TrackMyExpenses.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TrackMyExpenses/Models/Expense.cs
using System.ComponentModel.DataAnnotations;

namespace TrackMyExpenses.Models
{
    public class Expense
    {
        [Key]
        public int ExpenseId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public double Amount { get; set; }

        [Required]
        public DateTime ExpenseDate { get; set; }

        [Required]
        public string Category { get; set; }

        public int CategoryId { get; set; }
    }
}

TrackMyExpenses/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;

namespace TrackMyExpenses.Controllers
{
    public class ExpenseController : Controller
    {
        public IActionResult AddExpense()
        {
            return View();
        }
    }
}

TrackMyExpenses/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TrackMyExpenses.Models;

namespace TrackMyExpenses.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TrackMyExpenses/Views/Expense/AddExpense.cshtml
@model Expense


@{
    ViewData["Title"] = "Create New Expenses";
}

<form method="post" asp-action="Create">

    <div class="border p-5">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Record Your Expense</h2>
        </div>

        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="ExpenseDate"></label>
                <input asp-for="ExpenseDate" class="form-control datetimepicker" type="date"/>
                <span asp-validation-for="ExpenseDate" class="text-danger"></span>
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="Category"></label>
                <select asp-for="Category" class="form-control">
                    <option selected>Select</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="Amount"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
        </div>

        <br />

        <div class="w-12 btn-group" role="group">
            <input type="submit" class="btn btn-primary mx-1" value="Save" />
        </div>

    </div>

</form>

TrackMyExpenses/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TrackMyExpenses/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrackMyExpenses</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrackMyExpenses.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrackMyExpenses</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="AddExpense">Add Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TrackMyExpenses - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>